version: "3.8"
services:
  udemy-db: 
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - udemy
  udemy-back:
    image: joellord/udemy-back:1
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=udemy-db
    networks:
      - udemy
  udemy-front:
    image: joellord/udemy-front:1
    ports:
      - "8080:8080"
    environment: 
      - BASE_URL=http://localhost:3000
networks:
  udemy: 