apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  template:
    metadata:
      labels:
        app: hello-demo
    spec:
      containers:
      - name: server
        image: nginx:1.17
  selector:
    matchLabels:
      app: hello-demo
  replicas: 2